name: GithubMetrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 21 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: mrmasrozytlive/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: MrMasrozYTLIVE
          #template: terminal
          base: header, activity, repositories
          config_timezone: Europe/Moscow
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: MiTask
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          plugin_languages: yes
